#pragma once

#define ENTRY_HEIGHT 48
#define FILELIST_HEIGHT (240-MENU_HEADING_HEIGHT-MENU_BORDER_HEIGHT)
#define MENU_BORDER_HEIGHT 8
#define MENU_HEADING_HEIGHT 40
#define MAX_ENTRY_COUNT ((FILELIST_HEIGHT-(FILELIST_HEIGHT%ENTRY_HEIGHT))/ENTRY_HEIGHT)

#define BGColor HexColor(0xC87941)
#define BORDER_COLOR HexColor(0x290001)
#define BORDER_FOREGROUND HexColor(0xDBCBBD)
#define HIGHLIGHT_BGCOLOR HexColor(0x87431D)
#define HIGHLIGHT_FOREGROUND BGColor
#define FOREGROUND_COLOR BORDER_COLOR
